name: Lint

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
      - name: Install pnpm and typescript
        run: npm install -g pnpm && npm install -g typescript
      - name: Install dependencies
        run: pnpm install
      - name: Build Libs
        run: pnpm build:libs
      - name: Run lint
        run: pnpm run lint
